version: '3'
services:
  webserver:
    image: "nginx:stable"
    ports:
      - '${NGINX_PORT:-80}:${NGINX_PORT:-80}'
    volumes:
      - ./:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - mysql
    networks:
      - app-network
  php:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: docker/Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - '${PHP_PORT:-9000}:${PHP_PORT:-9000}'
    networks:
      - app-network
  mysql:
    image: mysql:8.0
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - '${DB_PORT:-3306}:${DB_PORT:-3306}'
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge