FROM php:8.2.8-fpm-alpine
RUN apk update && apk add \
    curl \
    libpng-dev \
    libxml2-dev \
    zip \
    unzip \
    nano
RUN docker-php-ext-install pdo \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install mysqli \
    && docker-php-ext-install opcache
COPY ./docker/custom.ini /usr/local/etc/php/conf.d
RUN chmod 777 -R /var/www/html
WORKDIR /var/www/html
